'use client';
import { Suspense, useState } from 'react';
import Link from 'next/link';
import { useSearchParams } from 'next/navigation';
import { Check, X, Plus, Dumbbell, Clock3, Flame } from 'lucide-react';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { useFitlog, type PlannedWorkout } from '@/components/fitlog-provider';
import { WorkoutImage, WorkoutStats, SortControl, EmptyPlan, LoadingWorkouts } from '@/components/workout-ui';
import { sortWorkouts, type SortKey } from '@/lib/workouts';
function PlanContent(){const query=useSearchParams();const [chosenTab,setTab]=useState<string|null>(null);const tab=chosenTab??(query.get('tab')==='saved'?'saved':'plan');const [sort,setSort]=useState<SortKey>('duration');const {plan,saved,loading,ready,error,remove,complete,addPlan}=useFitlog();const list=sortWorkouts(tab==='saved'?saved:plan,sort);const count=plan.length;const minutes=plan.reduce((n,w)=>n+w.duration,0);const calories=plan.reduce((n,w)=>n+w.caloriesBurned,0);const full=plan.filter(w=>!w.done).length>=5;
 return <main id="main" className="shell plan-page"><div className="plan-title"><h1>MY PLAN</h1><p>Cap of five lifts for today. Finish them, then load more.</p></div><section aria-label="Plan summary" className="metrics"><div><span><Dumbbell/>Exercises</span><strong>{count}</strong></div><div><span><Clock3/>Minutes</span><strong>{minutes}</strong></div><div><span><Flame/>Calories</span><strong>{calories}</strong></div></section><Tabs value={tab} onValueChange={setTab}><div className="plan-controls"><TabsList aria-label="Workout lists"><TabsTrigger value="plan">Today's Plan</TabsTrigger><TabsTrigger value="saved">Saved</TabsTrigger></TabsList><SortControl value={sort} onChange={setSort}/></div>{['plan','saved'].map(t=><TabsContent value={t} key={t}>{!ready||loading?<LoadingWorkouts/>:<>{error&&<p className="offline-note" role="status">Live library unavailable. Your stored workouts are still available.</p>}{list.length===0?<EmptyPlan/>:<div className="plan-list">{list.map(w=>{const done=tab==='plan'&&(w as PlannedWorkout).done;const already=plan.some(x=>x.id===w.id);return <article key={w.id} className={`plan-card${done?' is-done':''}`}><div className="plan-workout"><WorkoutImage w={w}/><div><h2>{w.name}{done&&<span className="done-label"><Check/>DONE</span>}</h2><p>{w.equipment}</p><WorkoutStats w={w}/></div></div><div className="plan-actions"><Link className="btn btn-small" href={`/workouts/${w.id}`}>View Details</Link>{tab==='plan'?<button className="btn btn-primary btn-small" disabled={done} onClick={()=>complete(w.id)}><Check/>{done?'Completed':'Mark as Done'}</button>:<button className="btn btn-primary btn-small" disabled={already||full} onClick={()=>addPlan(w)}>{already?<Check/>:<Plus/>}{already?'In your plan':full?'Plan is full':'Add to plan'}</button>}<button className="remove-button" aria-label={`Remove ${w.name} from ${tab==='saved'?'saved':"today’s plan"}`} onClick={()=>remove(w.id,tab)}><X/></button></div></article>;})}</div>}</>}</TabsContent>)}</Tabs></main>;
}
export default function MyPlan(){return <Suspense fallback={<main id="main" className="shell plan-page"><LoadingWorkouts/></main>}><PlanContent/></Suspense>;}
